version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/ci/cloudrunners"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/ci/gha-runner-vm"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/utilities/dot-project"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/utilities/labeler"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/utilities/landscape-mcp-server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/utilities/landscape-sync"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/ci/cloudrunners"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/ci/cloudrunners/gcp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/ci/gha-runner-image"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/utilities/dot-project"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/utilities/labeler"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/utilities/landscape-mcp-server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/ci/cluster/akamai"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/ci/iac/cluster"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/Ambassadors"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/Kubestronaut"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/Kubestronaut/Rendering"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/Kubestronaut/kubestronauts-coupons"
    schedule:
      interval: "weekly"
