apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: lke-gha-iad2
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 2.3.0
    chart: external-secrets
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
        crds:
          # -- If true, enable v1beta1 API version serving for ExternalSecret, ClusterExternalSecret, SecretStore, and ClusterSecretStore CRDs.
          # v1beta1 is deprecated. Only enable this for backward compatibility if you have existing v1beta1 resources.
          # Warning: This flag will be removed on 2026.05.01.
          unsafeServeV1Beta1: true
