apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickhouse-password
  namespace: clickhouse
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-secret-store
  target:
    name: clickhouse-password
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: clickhouse-password
