package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	"projects"

	"gopkg.in/yaml.v3"
)

func main() {
	var (
		slug         = flag.String("slug", "", "Project slug (required, lowercase with hyphens)")
		name         = flag.String("name", "", "Project display name (required)")
		description  = flag.String("description", "", "Project description (required)")
		repos        = flag.String("repos", "", "Comma-separated repository URLs (required)")
		website      = flag.String("website", "", "Project website URL")
		maturity     = flag.String("maturity", "sandbox", "Current maturity level: sandbox, incubating, graduated")
		maturityDate = flag.String("maturity-date", "", "Date of maturity acceptance (YYYY-MM-DD)")
		tocIssue     = flag.String("toc-issue", "", "TOC issue URL for acceptance")
		projectLead  = flag.String("project-lead", "", "GitHub handle of project lead")
		slackChannel = flag.String("slack-channel", "", "CNCF Slack channel (e.g., #my-project)")
		outputFile   = flag.String("output", "", "Output file path (default: stdout)")
	)
	flag.Parse()

	// Validate required fields
	var errors []string
	if *slug == "" {
		errors = append(errors, "-slug is required")
	}
	if *name == "" {
		errors = append(errors, "-name is required")
	}
	if *description == "" {
		errors = append(errors, "-description is required")
	}
	if *repos == "" {
		errors = append(errors, "-repos is required (comma-separated URLs)")
	}

	if len(errors) > 0 {
		fmt.Fprintln(os.Stderr, "Error:")
		for _, e := range errors {
			fmt.Fprintf(os.Stderr, "  - %s\n", e)
		}
		fmt.Fprintln(os.Stderr)
		flag.Usage()
		os.Exit(1)
	}

	// Parse maturity date
	var mDate time.Time
	if *maturityDate != "" {
		var err error
		mDate, err = time.Parse("2006-01-02", *maturityDate)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Invalid maturity-date format (use YYYY-MM-DD): %v\n", err)
			os.Exit(1)
		}
	} else {
		mDate = time.Now().Truncate(24 * time.Hour)
	}

	// Build project
	repoList := strings.Split(*repos, ",")
	for i := range repoList {
		repoList[i] = strings.TrimSpace(repoList[i])
	}

	project := projects.Project{
		SchemaVersion: "1.0.0",
		Slug:          *slug,
		Name:          *name,
		Description:   *description,
		Repositories:  repoList,
		MaturityLog: []projects.MaturityEntry{
			{
				Phase: *maturity,
				Date:  mDate,
				Issue: *tocIssue,
			},
		},
	}

	if *website != "" {
		project.Website = *website
	}
	if *projectLead != "" {
		project.ProjectLead = strings.TrimPrefix(*projectLead, "@")
	}
	if *slackChannel != "" {
		project.CNCFSlackChannel = *slackChannel
	}

	// Marshal to YAML
	data, err := yaml.Marshal(project)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to generate YAML: %v\n", err)
		os.Exit(1)
	}

	// Add header comment
	header := "# Generated by dot-project migrate tool\n# Review and customize before committing\n# See: https://github.com/cncf/automation/tree/main/utilities/dot-project\n\n"
	output := header + string(data)

	if *outputFile != "" {
		if err := os.WriteFile(*outputFile, []byte(output), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to write file: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "Generated %s\n", *outputFile)
	} else {
		fmt.Print(output)
	}

	// Validate the generated project
	validationErrors := projects.ValidateProjectStruct(project)
	if len(validationErrors) > 0 {
		fmt.Fprintln(os.Stderr, "\nWarning: generated project.yaml has validation issues:")
		for _, e := range validationErrors {
			fmt.Fprintf(os.Stderr, "  - %s\n", e)
		}
	} else {
		fmt.Fprintln(os.Stderr, "Generated project.yaml passes validation.")
	}
}
