apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: sbom-cluster
spec:
  replicas: 3
  shards: 2
  keeperClusterRef:
    name: sbom-keeper
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500Gi
  containerTemplate:
    image:
      repository: docker.io/clickhouse/clickhouse-server
      tag: "26.1.3"
    resources:
      requests:
        cpu: "2"
        memory: "8Gi"
      limits:
        cpu: "4"
        memory: "16Gi"
    volumeMounts:
      - mountPath: /etc/clickhouse-server/config.d
        subPath: listen_host_config.xml
        name: listen-host-config
        readOnly: true
  podTemplate:
    volumes:
      - name: listen-host-config
        configMap:
          name: listen-host-config
  settings:
    defaultUserPassword:
      secret:
        name: clickhouse-password
        key: password
    tls:
      enabled: false
      required: false
---
apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: sbom-keeper
spec:
  replicas: 3
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  containerTemplate:
    image:
      repository: docker.io/clickhouse/clickhouse-keeper
      tag: "26.1.3"
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    volumeMounts:
      - mountPath: /etc/clickhouse-server/config.d
        subPath: listen_host_config.xml
        name: listen-host-config
        readOnly: true
  podTemplate:
    topologyZoneKey: topology.kubernetes.io/zone
    volumes:
      - name: listen-host-config
        configMap:
          name: listen-host-config
  settings:
    tls:
      enabled: false
      required: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: listen-host-config
data:
  listen_host_config.xml: |
    <clickhouse>
        <listen_host>0.0.0.0</listen_host>
    </clickhouse>
