apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oracle-2cpu-8gb-arm64
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oci-gha-arm64-runners
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/cncf/automation.git'
    targetRevision: main
    path: ci/cluster/oci-arm64/runners/2cpu-8gb/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
