apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-arc-secret
  namespace: arc-systems
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-secret-store
  target:
    name: github-arc-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: github-arc-secret
