apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linode-credentials
  namespace: karpenter
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-secret-store
  target:
    name: linode-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: linode-credentials
