apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oci-api-key
  namespace: arc-systems
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-secret-store
  target:
    name: oci-api-key
    creationPolicy: Owner
    template:
      data:
        oci_api_key.pem: "{{ .oci_api_key | toString }}"
  data:
  - secretKey: oci_api_key
    remoteRef:
      key: oci-api-key
