run:
	go run main.go https://raw.githubusercontent.com/mrbobbytables/cncf-automation/refs/heads/label-config/utilities/labeler/labels.yaml cncf automation 95 "/tag foo"
image:
	docker build -t gha-labeler:latest .