name: Validate Project Metadata

on:
  pull_request:
    paths:
      - 'project.yaml'
      - 'maintainers.yaml'
  push:
    branches: [main]
    paths:
      - 'project.yaml'
      - 'maintainers.yaml'

permissions:
  contents: read

jobs:
  validate-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          fetch-depth: 0

      - uses: cncf/automation/.github/actions/validate-project@979abb1e07fa1b6f2b4e77200f6a698cdd86e59c
        with:
          project_file: 'project.yaml'

  validate-maintainers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: cncf/automation/.github/actions/validate-maintainers@979abb1e07fa1b6f2b4e77200f6a698cdd86e59c
        with:
          maintainers_file: 'maintainers.yaml'
          # Disabled until the LFX LLT issue is resolved. Validation is done manually for now.
          verify_maintainers: 'false'
        env:
          LFX_AUTH_TOKEN: ${{ secrets.LFX_AUTH_TOKEN }}
