# .project metadata for [YOUR PROJECT NAME]
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project
#
# Instructions:
#   1. Replace all [PLACEHOLDER] values with your project's information
#   2. Remove any optional sections you don't need
#   3. Ensure your project validates: see the CI workflow in .github/workflows/

schema_version: "1.0.0"
slug: "my-project"              # REQUIRED: lowercase identifier (a-z, 0-9, hyphens)
name: "My Project"              # REQUIRED: display name
description: ""                 # REQUIRED: one-line project description
type: "project"                 # Optional: project, platform, specification, etc.
project_lead: "github-handle"   # Optional: GitHub handle of primary contact
cncf_slack_channel: "#my-project" # Optional: CNCF Slack channel

maturity_log:                   # REQUIRED: at least one entry
  - phase: "sandbox"            # sandbox, incubating, graduated, archived
    date: "2024-01-15T00:00:00Z"
    issue: "https://github.com/cncf/toc/issues/XXX"

repositories:                   # REQUIRED: at least one repository URL
  - "https://github.com/my-org/my-project"

website: "https://my-project.io"
artwork: "https://github.com/cncf/artwork/tree/master/projects/my-project"

# adopters:                      # Optional: link to adopters list
#   path: "ADOPTERS.md"

# package_managers:              # Optional: registry identifiers
#   docker: "my-org/my-project"
#   npm: "my-project"

social:                         # Optional
  twitter: "https://twitter.com/myproject"
  slack: "https://myproject.slack.com"

mailing_lists:                  # Optional
  - "my-project-dev@lists.cncf.io"

audits:                         # Optional (recommended for incubating+)
  - date: "2024-01-01T00:00:00Z"
    type: "security"
    url: "https://example.com/audit-report.pdf"

security:                       # Optional
  policy:
    path: "SECURITY.md"
  contact: "security@my-project.io"

governance:                     # Optional
  contributing:
    path: "CONTRIBUTING.md"
  codeowners:
    path: "CODEOWNERS"
  # Governance DD items (optional):
  # vendor_neutrality_statement:
  #   path: "docs/vendor-neutrality.md"
  # decision_making_process:
  #   path: "docs/decision-making.md"
  # roles_and_teams:
  #   path: "docs/roles-and-teams.md"
  # code_of_conduct:
  #   path: "CODE_OF_CONDUCT.md"
  # sub_project_list:
  #   path: "docs/subprojects.md"
  # sub_project_docs:
  #   path: "docs/subproject-docs.md"
  # contributor_ladder:
  #   path: "docs/contributor-ladder.md"
  # change_process:
  #   path: "docs/change-process.md"
  # comms_channels:
  #   path: "docs/communication.md"
  # community_calendar:
  #   path: "docs/calendar.md"
  # contributor_guide:
  #   path: "docs/contributor-guide.md"
  # maintainer_lifecycle:       # Optional: maintainer lifecycle documentation
  #   onboarding_doc:
  #     path: "docs/onboarding.md"
  #   progression_ladder:
  #     path: "docs/progression.md"
  #   mentoring_program:
  #     - "https://example.com/mentoring"
  #   offboarding_policy:
  #     path: "docs/offboarding.md"

legal:                          # Optional
  license:
    path: "LICENSE"
  # identity_type:               # Optional: contributor identity agreements
  #   has_dco: true              # DCO can be used alone
  #   has_cla: false             # CLA requires DCO
  #   dco_url:
  #     path: "https://developercertificate.org/"
  #   cla_url:
  #     path: "https://example.com/cla"

documentation:                  # Optional
  readme:
    path: "README.md"

# landscape:                    # Optional: CNCF Landscape location
#   category: "App Definition and Development"
#   subcategory: "Database"
