apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-altinity-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oke-cncf-automation
spec:
  project: default
  source:
    repoURL: https://helm.altinity.com
    chart: altinity-clickhouse-operator
    targetRevision: 0.26.0
    helm:
      values: |
        crdHook:
          enabled: true
          image:
            repository: docker.io/bitnami/kubectl
        operator:
          image:
            registry: "docker.io"
        metrics:
          image:
            registry: "docker.io"
        fullnameOverride: clickhouse-altinity-operator
        serviceMonitor:
          enabled: true
        configs:
          files:
            config.yaml:
              watch:
                namespaces: ["clickhouse-altinity", "seebom"]
          templatesdFiles:
            001-templates.json.example: |
              {
                "apiVersion": "clickhouse.altinity.com/v1",
                "kind": "ClickHouseInstallationTemplate",
                "metadata": {
                  "name": "01-default-volumeclaimtemplate"
                },
                "spec": {
                  "templates": {
                    "volumeClaimTemplates": [
                      {
                        "name": "chi-default-volume-claim-template",
                        "spec": {
                          "accessModes": [
                            "ReadWriteOnce"
                          ],
                          "resources": {
                            "requests": {
                              "storage": "2Gi"
                            }
                          }
                        }
                      }
                    ],
                    "podTemplates": [
                      {
                        "name": "chi-default-oneperhost-pod-template",
                        "distribution": "OnePerHost",
                        "spec": {
                          "containers" : [
                            {
                              "name": "clickhouse",
                              "image": "docker.io/clickhouse/clickhouse-server:23.8",
                              "ports": [
                                {
                                  "name": "http",
                                  "containerPort": 8123
                                },
                                {
                                  "name": "client",
                                  "containerPort": 9000
                                },
                                {
                                  "name": "interserver",
                                  "containerPort": 9009
                                }
                              ]
                            }
                          ]
                        }
                      }
                    ]
                  }
                }
              }
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse-altinity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
