apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bomhort
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oke-cncf-automation
spec:
  project: default
  source:
    repoURL: ghcr.io/seebom-labs/bomhort/charts
    chart: bomhort
    targetRevision: 0.6.1
    helm:
      values: |
        cleanBatchJobs: false
        clickhouse:
          database: bomhort
          host: chi-bomhort-clickhouse-bomhort-cluster-0-0
          installation:
            podTemplate:
              containerImage: docker.io/clickhouse/clickhouse-server:24.8
              resources:
                limits:
                  cpu: "4"
                  memory: 16Gi
                requests:
                  cpu: "2"
                  memory: 8Gi
            volumeClaimTemplate:
              dataStorage: 500Gi
              logStorage: 10Gi
          port: 9000
          user: default
          userPasswordSecret:
            enabled: true
            key: password
            secretName: clickhouse-password
        gitSync:
          enabled: false
        image:
          registry: ghcr.io
          repository: seebom-labs/bomhort
          tag: 0.6.1
        sbomSource:
          mountPath: /data/sboms
          pvcName: bomhort-sbom-data
          storageSize: 20Gi
        seedJob:
          cncfExceptionsURL: https://cncf-license-exceptions.netlify.app/exceptions.json
          sbomBranch: main
          sbomRepo: https://github.com/cncf/sbom.git
        s3:
          buckets: '[{"name":"cncf-subproject-sboms","endpoint":"us-iad-18.linodeobjects.com","region":"us-iad-18"},{"name":"cncf-project-sboms","endpoint":"us-iad-18.linodeobjects.com","region":"us-iad-18"}]'
  destination:
    server: https://kubernetes.default.svc
    namespace: bomhort
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: batch
      kind: Job
      jqPathExpressions:
        - .status
        - .spec.selector
        - .spec.template.metadata.labels
