apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bomhort
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oke-cncf-automation
spec:
  project: default
  sources:
    - repoURL: ghcr.io/seebom-labs/bomhort/charts
      chart: bomhort
      targetRevision: 0.7.1
      helm:
        valueFiles:
          - $values/ci/cluster/services/helm-values/bomhort-values.yaml
    - repoURL: https://github.com/cncf/automation.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: bomhort
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: batch
      kind: Job
      jqPathExpressions:
        - .status
        - .spec.selector
        - .spec.template.metadata.labels
