apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-barman-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oke-cncf-automation
spec:
  project: default
  source:
    chart: plugin-barman-cloud
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.7.0
    helm:
      releaseName: barman-cloud
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
 