apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oke-cncf-automation
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway
  source:
    path: ci/cluster/services/manifests/envoy-gateway
    repoURL: https://github.com/cncf/automation
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m
