apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oke-cncf-automation
spec:
  destination:
    namespace: guac
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: guac
    repoURL: https://kusaridev.github.io/helm-charts
    targetRevision: 0.6.2
    helm:
      values: |
        guac:
          guacImage:
            tag: v1.0.0
          ingress:
            enabled: true
            ingressClassName: nginx
            webuiHostname: guac.k8c.io
            apiHostname: api.guac.k8c.io
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
