apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seebom
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    notifications.argoproj.io/subscribe.slack: internal-gha-argo
  labels:
    cluster: oke-cncf-automation
spec:
  project: default
  source:
    repoURL: ghcr.io/seebom-labs/seebom/charts/
    targetRevision: 0.1.0
    chart: seebom
    helm:
      values: |
        gitSync:
          enabled: true
          image: registry.k8s.io/git-sync/git-sync:v4.4.0
          repo: "https://github.com/cncf/sbom.git"
          secretName: github-credentials
        clickhouse:
          host: chi-seebom-cluster-0-0
          port: 9000
          database: seebom
          user: default
          userPasswordSecret:
            enabled: true
            secretName: clickhouse-password
            key: password
  destination:
    server: https://kubernetes.default.svc
    namespace: seebom
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
