name: Auto Label Issues and PRs

on:
  issue_comment:
    types: [created, edited]
  pull_request_target:
    types: [opened, edited, reopened]
  issues:
    types: [opened, edited, reopened]

jobs:
  label:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          separator: ","

      - name: Run labeler action for PR
        if: ${{ github.event.pull_request }}
        uses: ./.github/actions/labeler-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: https://raw.githubusercontent.com/cncf/automation/refs/heads/main/utilities/labeler/labels.yaml
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.pull_request.number }}
          comment_body: ${{ github.event.pull_request.body }}
          changed_files: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Run labeler action for Issue
        if: ${{ !github.event.pull_request }}
        uses: ./.github/actions/labeler-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: https://raw.githubusercontent.com/cncf/automation/refs/heads/main/utilities/labeler/labels.yaml
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.issue.number }}
          comment_body: ${{ github.event.comment.body }}
