name: Auto Label Issues and PRs

on:
  issue_comment:
    types: [created, edited]
  pull_request_target:
    types: [opened, edited, reopened]
  issues:
    types: [opened, edited, reopened]

jobs:
  label:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          separator: ","

      - name: Run labeler action for PR
        if: ${{ github.event.pull_request }}
        uses: ./.github/actions/labeler-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: https://raw.githubusercontent.com/cncf/automation/refs/heads/main/.github/labels.yaml
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.pull_request.number }}
          comment_body: ""
          changed_files: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Run labeler action for Issue
        if: >-
          ${{
            !github.event.pull_request &&
            (
              github.event_name != 'issue_comment' ||
              (
                !startsWith(github.event.comment.body, '/kind') &&
                !startsWith(github.event.comment.body, '/priority') &&
                !startsWith(github.event.comment.body, '/status') &&
                !startsWith(github.event.comment.body, '/area') &&
                !startsWith(github.event.comment.body, '/help') &&
                !startsWith(github.event.comment.body, '/remove-kind') &&
                !startsWith(github.event.comment.body, '/remove-priority') &&
                !startsWith(github.event.comment.body, '/remove-status') &&
                !startsWith(github.event.comment.body, '/remove-area') &&
                !startsWith(github.event.comment.body, '/remove-help') &&
                !contains(github.event.comment.body, '\n/kind') &&
                !contains(github.event.comment.body, '\n/priority') &&
                !contains(github.event.comment.body, '\n/status') &&
                !contains(github.event.comment.body, '\n/area') &&
                !contains(github.event.comment.body, '\n/help') &&
                !contains(github.event.comment.body, '\n/remove-kind') &&
                !contains(github.event.comment.body, '\n/remove-priority') &&
                !contains(github.event.comment.body, '\n/remove-status') &&
                !contains(github.event.comment.body, '\n/remove-area') &&
                !contains(github.event.comment.body, '\n/remove-help')
              )
            )
          }}
        uses: ./.github/actions/labeler-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: https://raw.githubusercontent.com/cncf/automation/refs/heads/main/.github/labels.yaml
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.issue.number }}
          comment_body: ${{ github.event.comment.body }}
