---
name: Build CloudRunner Docker Images

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [main]
    paths:
      - 'ci/cloudrunners/Dockerfile*'
      - 'ci/cloudrunners/oci/**'
  pull_request:
    branches: [main]
    paths:
      - 'ci/cloudrunners/Dockerfile*'
      - 'ci/cloudrunners/oci/**'
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # IMAGE_NAME maps to the Docker image name
  IMAGE_NAME: cncf/gha-cloudrunner

jobs:
  build-cloudrunner-images:
    outputs:
      image: ${{ steps.image.outputs.image }}
      digest: ${{ steps.build-and-push.outputs.digest }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Cloudrunner Docker image
        id: build-and-push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ./ci/cloudrunners/
          platforms: linux/amd64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          file: ./ci/cloudrunners/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}

      # Uses the identity token to provision an ephemeral certificate
      # against the sigstore community Fulcio instance.
      - name: Sign the published Cloudrunner Docker image
        if: ${{ github.event_name != 'pull_request' }}
        run: cosign sign -y ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}

      - name: Output image
        id: image
        run: echo "image=${REGISTRY}/${IMAGE_NAME}" >> "$GITHUB_OUTPUT"

  # Generate SLSA provenance for the image
  # Upload the provenance to ghcr.io
  provenance:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [build-cloudrunner-images]
    permissions:
      id-token: write  # For signing.
      actions: read    # For reading workflow info.
      packages: write  # For uploading attestations.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ${{ needs.build-cloudrunner-images.outputs.image }}
      digest: ${{ needs.build-cloudrunner-images.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  # Verify the created provenance attestation.
  verify:
    # NOTE: this name is used as the status check name and by protected
    # branches for required status checks. It should have a unique name among
    # other pre-submits.
    name: verify container provenance
    needs: [build-cloudrunner-images, provenance]
    permissions:
      packages: read  # For reading attestations.
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
        with:
          cosign-release: 'v2.2.3'
      - env:
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_NAME: ${{ needs.build-cloudrunner-images.outputs.image }}
          IMAGE_DIGEST: ${{ needs.build-cloudrunner-images.outputs.digest }}
        run: |
          cosign version
          cosign verify-attestation \
            --certificate-oidc-issuer="https://token.actions.githubusercontent.com" \
            --certificate-identity-regexp="^https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@refs/tags/v[0-9]+.*$" \
            --type slsaprovenance "${{ env.IMAGE_NAME }}@${{env.IMAGE_DIGEST}}"
      # TODO (github.com/slsa-framework/slsa-verifier/issues/92):
      #       Add step to verify using slsa-verifier

  # Test the published image by running it and see if the VM is created.
  test-image:
    needs: build-cloudrunner-images
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      REGION: us-sanjose-1
      AVAILABILITY_DOMAIN: bzBe:US-SANJOSE-1-AD-1
      SUBNET_ID: ocid1.subnet.oc1.us-sanjose-1.aaaaaaaahgdslvujnywu3hvhqbvgz23souseseozvypng7ehnxgcotislubq
      FALLBACK_REGION: us-ashburn-1
      FALLBACK_AVAILABILITY_DOMAIN: bzBe:US-ASHBURN-AD-2
      FALLBACK_SUBNET_ID: ocid1.subnet.oc1.iad.aaaaaaaagygdzd4xgbz4xhqhvnbxnoemhjd5ick7vodx4ghk4kg6a6c4xh5q
    strategy:
      fail-fast: false
      matrix:
        runner: ["amd64", "arm64", "gpu-a10-1", "gpu-a10-2"]
        include:
          - runner: "amd64"
            arch: "amd64"
            shape: "VM.Standard.E6.Flex,VM.Standard.E5.Flex,VM.Standard.E4.Flex"
            ocpus: 2
            memory: 8.0
          - runner: "arm64"
            arch: "arm64"
            shape: "VM.Standard.A1.Flex"
            ocpus: 2
            memory: 8.0
          - runner: "gpu-a10-1"
            arch: "amd64"
            shape: "VM.GPU.A10.1"
            ocpus: 0   # Not a flex type, so ocpus and memory are determined by the shape
            memory: 0
          - runner: "gpu-a10-2"
            arch: "amd64"
            shape: "VM.GPU.A10.2"
            ocpus: 0   # Not a flex type, so ocpus and memory are determined by the shape
            memory: 0
    steps:
      - name: Test the published Cloudrunner Docker image
        run: |
          OCI_CONFIG_FILE="${{ github.workspace}}/.oci/config"
          OCI_KEY_FILE="${{ github.workspace}}/.oci/oci_api_key.pem"
          mkdir -p "${{ github.workspace}}/.oci"

          cat > ${OCI_CONFIG_FILE} << EOF
          [DEFAULT]
          user=${{ secrets.OCI_CLI_USER }}
          fingerprint=${{ secrets.OCI_CLI_FINGERPRINT }}
          tenancy=${{ secrets.OCI_CLI_TENANCY }}
          region=${{ secrets.OCI_CLI_REGION }}
          key_file=/root/.oci/oci_api_key.pem
          EOF

          echo "${{ secrets.OCI_CLI_KEY_CONTENT }}" > ${OCI_KEY_FILE}

          chmod 600 ${OCI_KEY_FILE} ${OCI_CONFIG_FILE}

          docker run -v ${{ github.workspace}}/.oci:/root/.oci \
            ${{ needs.build-cloudrunner-images.outputs.image }}@${{ needs.build-cloudrunner-images.outputs.digest }} \
            --arch=${{ matrix.arch }} \
            --shape=${{ matrix.shape }} \
            --shape-ocpus=${{ matrix.ocpus }} \
            --shape-memory-in-gbs=${{ matrix.memory }} \
            --region=${{ env.REGION }} \
            --availability-domain=${{ env.AVAILABILITY_DOMAIN }} \
            --subnet-id=${{ env.SUBNET_ID }} \
            --fallback-region=${{ env.FALLBACK_REGION }} \
            --fallback-availability-domain=${{ env.FALLBACK_AVAILABILITY_DOMAIN }} \
            --fallback-subnet-id=${{ env.FALLBACK_SUBNET_ID }}
