name: Test VM Runners

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner name.'
        required: true
        type: string
        default: oracle-vm-2cpu-8gb-x86-64
      test_gpu:
        description: 'Test GPU Runners'
        required: false
        type: choice
        options:
        - 'yes'
        - 'no'
        default: 'no'

permissions:
  contents: read

jobs:
  test-runner:
    runs-on: ${{ github.event.inputs.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run uname to verify architecture
        run: |
          uname -a
          lsb_release -a
          id
          cat /etc/group
          cat /proc/cpuinfo

      - name: Run a basic workload
        run: |
          echo "Testing Runner"
          echo "CPU Info:"
          lscpu
          docker run hello-world

      - name: Check local disk 
        run: |
         df -h /

      - name: Run kind cluster
        run: ${{ github.workspace }}/.github/scripts/test_with_kind_cluster.sh

  test-a10-1-gpu-runner:
    runs-on:
      labels: oracle-vm-gpu-a10-1
      group: GPUs
    if: ${{ github.event.inputs.test_gpu == 'yes' }}
    steps:
      - name: checkout gpus
        run: |
          echo "[*] Detailed GPU query"
          nvidia-smi -q

          echo "[*] Specific information"
          nvidia-smi --query-gpu=name,driver_version,memory.total --format=csv

          echo "[*] NVIDIA driver version"
          cat /proc/driver/nvidia/version

  test-a10-2-gpu-runner:
    runs-on:
      labels: oracle-vm-gpu-a10-2
      group: GPUs
    if: ${{ github.event.inputs.test_gpu == 'yes' }}
    steps:
      - name: checkout gpus
        run: |
          echo "[*] Detailed GPU query"
          nvidia-smi -q

          echo "[*] Specific information"
          nvidia-smi --query-gpu=name,driver_version,memory.total --format=csv

          echo "[*] NVIDIA driver version"
          cat /proc/driver/nvidia/version
