name: "Labeler Action"
description: "A reusable action to label issues and PRs using a Docker container."

inputs:
  labels:
    description: "label config"
    required: true
  owner:
    description: "The repository owner."
    required: true
  repo:
    description: "The repository name."
    required: true
  issue_number:
    description: "The issue or PR number."
    required: true
  comment_body:
    description: "The body of the comment triggering the action."
    required: true
  changed_files:
    description: "comma separated list of files"
    required: false

runs:
  using: "docker"
  image: "docker://ghcr.io/cncf/gha-labeler:main"
  args:
    - "${{ inputs.labels }}"
    - "${{ inputs.owner }}"
    - "${{ inputs.repo }}"
    - "${{ inputs.issue_number }}"
    - "${{ inputs.comment_body }}"
    - "${{ inputs.changed_files }}"
